### PR TITLE
Work on updating deprecations

### LINKED ISSUE #2342: Kernel test classes must specify the #[RunTestsInSeparateProcesses] attribute
### Task Description

There are new deprecations showing up when testing on Drupal 11.3.x (i.e. 11.x). Specifically, 

> Kernel test classes must specify the #[RunTestsInSeparateProcesses] attribute, not doing so is deprecated in drupal:11.3.0 and will throw an exception in drupal:12.0.0. See https://www.drupal.org/node/3548485

Is being triggered by every single one of our Kernel Tests 🙈 

### Branch Name

tv4g9-2342-drupal11xDeprecations

### PR DESCRIPTION
**Pull request by laceysanderson**
# Tripal 4 Core Dev Task

## Description

See the linked issues but essentially this is me going hog on the deprecations that are currently outstanding and also harmonizing group names at the same time since I'm already in each kernel test.

Specific tasks completed:
- [x] Handled the deprecations listed below in all test files.
- [x] add one iteration of testing on Drupal 11.x (same as the devcontainer) so we see these deprecations in Github.
- [x] harmonized all the test groups
- [x] ensured all test namespaces matched their path
- [x] fixed a few path errors for tests
- [x] some automated coding standard changes in tests

### Deprecations

Deprecations Addressed:
- Kernel test classes must specify the #[RunTestsInSeparateProcesses] attribute, not doing so is deprecated in drupal:11.3.0 and will throw an exception in drupal:12.0.0. See https://www.drupal.org/node/3548485
- Functional and FunctionalJavascript test classes must specify the #[RunTestsInSeparateProcesses] attribute, not doing so is deprecated in drupal:11.3.0 and will throw an exception in drupal:12.0.0. See https://www.drupal.org/node/3548485
- Unit test classes must specify the #[RunTestsInSeparateProcesses] attribute, not doing so is deprecated in drupal:11.3.0 and will throw an exception in drupal:12.0.0. See https://www.drupal.org/node/3548485
- getMockForAbstractClass() is deprecated and will be removed in PHPUnit 12 without replacement

Deprecations NOT Addressed (see #2352):
- field_group_module_implements_alter without a #[LegacyModuleImplementsAlter] attribute is deprecated in drupal:11.2.0 and removed in drupal:12.0.0. See https://www.drupal.org/node/3496788
- Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future. Do the same in implementation "Drupal\devel\Twig\Extension\Debug" now to avoid errors or add an explicit @return annotation to suppress this message.
- Providing a file for theme hook tripal_entity_type is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500
- Providing template_preprocess_tripal_entity_type() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125
- Providing a file for theme hook tripal_entity is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500
- Providing template_preprocess_tripal_entity() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125
- Providing a file for theme hook tripal_entity_content_add_list is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

### Groups

This PR also harmonizes the testing groups. They are now as follows:

#### Tripal or Chado specific instances of plugins

 - tripal-content (30 tests)
 - tripal-dbx (369 tests)
 - tripal-field (46 tests)
 - tripal-importer (34 tests)
 - tripal-publish (7 tests)
 - tripal-storage (37 tests)
 - tripal-term (11 tests)
 - chado-field (39 tests)
 - chado-importer (15 tests)
 - chado-publish (3 tests)
 - chado-schema (317 tests)
 - chado-storage (25 tests)
 - chado-term (6 tests)

#### Importers

 - chado-importer (15 tests)
 - tripal-importer (34 tests)
 - importer-datafiles (2 tests)
 - importer-fasta (1 test)
 - importer-gff3 (1 test)
 - importer-newick (1 test)
 - importer-obo (2 tests)
 - importer-phylotree (1 test)
 - importer-pub (3 tests)
 - importer-taxonomy (1 test)

#### Biological Concepts

 - bio-cv (10 tests)
 - bio-feature (2 tests)
 - bio-organism (8 tests)
 - bio-phylogeny (4 tests)
 - bio-pub (2 tests)

#### General Concepts

 - access (8 tests)
 - access-entity (3 tests)
 - autocomplete (9 tests)
 - consistency (2 tests)
 - drush-command (1 test)
 - field-discovery (2 tests)
 - form (4 tests)
 - layout (7 tests)
 - legacy-api (23 tests)
 - render (8 tests)

#### Services and Plugins

*Note: Only plugins that we don't plan or see a reason to have both a chado and tripal implementation go in this category.*

 - service (4 tests)
 - service-chado-custom-table (2 tests)
 - service-citation (1 test)
 - service-collection (15 tests)
 - service-dashboard (1 test)
 - service-file-retriever (5 tests)
 - service-job (4 tests)
 - service-token-parser (16 tests)
 - plugin-chado-buddy (10 tests)

#### BioDB Tasks

 - biodb-lock (15 tests)
 - biodb-task (13 tests)
 - task-cloner (1 test)
 - task-installer (6 tests)
 - task-preparer (2 tests)
 - task-remover (1 test)
 - task-renamer (1 test)

## Testing?

This only touches automated testing so there should not be any need for manual testing.

For confirmation that the deprecations are resolved, you can see the Drupal 11.x-dev PHP 8.4 PostgreSQL 17 workflow run.

**Kernel** tests will now have all deprecations fixed. You can run just this test suite using:

```
phpunit --testsuite kernel
PHPUnit 11.5.42 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.14
Configuration: /var/www/drupal/web/modules/contrib/tripal/phpunit.xml

.....................I.........................................  63 / 494 ( 12%)
............................................................... 126 / 494 ( 25%)
............................................................... 189 / 494 ( 38%)
............................................................... 252 / 494 ( 51%)
............................................................... 315 / 494 ( 63%)
............................................................... 378 / 494 ( 76%)
............................................................... 441 / 494 ( 89%)
..............................................I......           494 / 494 (100%)

Time: 21:23.301, Memory: 36.00 MB

OK, but there were issues!
Tests: 494, Assertions: 20985, Incomplete: 2.
```

**Unit** tests will also have no outstanding deprecations.

```
phpunit --testsuite unit
PHPUnit 11.5.42 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.14
Configuration: /var/www/drupal/web/modules/contrib/tripal/phpunit.xml

.............................................                     45 / 45 (100%)

Time: 00:18.471, Memory: 18.00 MB

OK (45 tests, 154 assertions)
```

**Functional** tests will now only have the unaddressed deprecations. You can run just this test suite using the following command. NOTE: I have removed the "targetted by" entries for each deprecation for easier reading.

```
PHPUnit 11.5.42 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.14
Configuration: /var/www/drupal/web/modules/contrib/tripal/phpunit.xml

DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD......IIII.DDDDDDDD 65 / 66 ( 98%)
D                                                                 66 / 66 (100%)

Time: 08:22.204, Memory: 24.00 MB

55 tests triggered 7 deprecations:

1) /var/www/drupal/web/core/lib/Drupal/Core/Hook/HookCollectorPass.php:591
field_group_module_implements_alter without a #[LegacyModuleImplementsAlter] attribute is deprecated in drupal:11.2.0 and removed in drupal:12.0.0. See https://www.drupal.org/node/3496788

2) /var/www/drupal/vendor/symfony/error-handler/DebugClassLoader.php:347
Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future. Do the same in implementation "Drupal\devel\Twig\Extension\Debug" now to avoid errors or add an explicit @return annotation to suppress this message.

3) /var/www/drupal/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:52
Providing a file for theme hook tripal_entity_type is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

4) /var/www/drupal/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:52
Providing template_preprocess_tripal_entity_type() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

5) /var/www/drupal/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:52
Providing a file for theme hook tripal_entity is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500

6) /var/www/drupal/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:52
Providing template_preprocess_tripal_entity() is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3504125

7) /var/www/drupal/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:52
Providing a file for theme hook tripal_entity_content_add_list is deprecated in drupal:11.3.0 and is removed from drupal:12.0.0. Use initial preprocess for template_preprocess instead. See https://www.drupal.org/node/3549500


FAILURES!
Tests: 66, Assertions: 7157, Failures: 0, Deprecations: 7, Incomplete: 6.
```

**NOTE: The Drupal 11.x-dev PHP 8.4 PostgreSQL 17 workflow run is not expected to pass since there are still 7 unaddressed deprecations 🙈**

### CODE REVIEW

File: tripal/tests/src/Functional/Permissions/TripalRoutePermissionsTest.php [hunk 1]
```diff
@@ -14,24 +18,22 @@
...
+#[Group('access')]
+#[RunTestsInSeparateProcesses]
 class TripalRoutePermissionsTest extends BrowserTestBase {
 
   use TripalTestTrait;
 
-  // protected $htmlOutputEnabled = TRUE;
+  /**
+   * Protected $htmlOutputEnabled = TRUE;.
+   */
```
Comment (dsenalik) [inline tripal/tests/src/Functional/Permissions/TripalRoutePermissionsTest.php]: Shouldn't we just delete this?
```suggestion
```

File: tripal/tests/src/Functional/Permissions/TripalRoutePermissionsTest.php [hunk 2]
```diff
@@ -49,11 +51,11 @@ public function testTripalAdminPages() {
       // Under Drupal ~10.2, if there are no extensions present, and there aren't, then
       // we won't be able to access the 'admin/tripal/extension' menu, even as admin.
       // To test, we would have to create an extension first.
-      // 'Extensions' => 'admin/tripal/extension',
+      // 'Extensions' => 'admin/tripal/extension',.
```
Comment (dsenalik) [inline tripal/tests/src/Functional/Permissions/TripalRoutePermissionsTest.php]:
```suggestion
      // 'Extensions' => 'admin/tripal/extension'.
```

File: tripal/tests/src/Functional/Plugin/TripalDefaultVocabularyTest.php [hunk 3]
```diff
@@ -104,7 +100,7 @@ public function testTripalDefaultVocabulary() {
     // Make sure the getter works.
     $this->assertTrue($cc->getLabel() == $GO_cc_label, "The TripalVocabulary object did not return a correct label.");
 
-    // Associate the IDSpace with the vocabulary,
+    // Associate the IDSpace with the vocabulary,.
```
Comment (dsenalik) [inline tripal/tests/src/Functional/Plugin/TripalDefaultVocabularyTest.php]:
```suggestion
    // Associate the IDSpace with the vocabulary.
```

File: tripal/tests/src/Functional/Services/TripalFieldCollectionTest.php [hunk 4]
```diff
@@ -163,7 +162,7 @@ public function testTripalFieldCollection() {
     $this->assertIsInt($defaults['cardinality'], 'The cardinality element is not an integer');
     $this->assertIsArray($defaults['storage_settings']['storage_plugin_settings'], 'The storage_plugin_settings element should be an array');
 
-    // Make sure the setFieldDefDefaults functions doesn't change any valid values
+    // Make sure the setFieldDefDefaults functions doesn't change any valid values.
```
Comment (dsenalik) [inline tripal/tests/src/Functional/Services/TripalFieldCollectionTest.php]:
```suggestion
    // Make sure the setFieldDefDefaults function doesn't change any valid values.
```
Can't help fixing this

File: tripal/tests/src/Kernel/TripalTestKernelBase.php [hunk 5]
```diff
@@ -48,35 +52,29 @@ abstract class TripalTestKernelBase extends KernelTestBase {
...
+   *   then include in your kernel tests and this method supports that.
+   *   Supported keys are:
    *   - TripalTerm
    *   - TripalEntity
    *   - TripalField
-   *   - TripalImporter
+   *   - TripalImporter.
    *
    * @return void
+   *   All changes are stored in variables rather then returned.
```
Comment (dsenalik) [inline tripal/tests/src/Kernel/TripalTestKernelBase.php]:
```suggestion
   *   All changes are stored in variables rather than returned.
```

File: tripal_chado/tests/src/Functional/Services/ChadoTripalPublishTest.php [hunk 6]
```diff
@@ -654,27 +676,26 @@ public function testChadoTripalPublishService() {
...
     //
-
     // Create and publish the contacts and the project.
     $contact_db = $idsmanager->loadCollection('TCONTACT', "chado_id_space");
     $person_term_id = $contact_db->getTerm('0000003')->getInternalId();
     $contact_id1 = $this->addChadoContact($chado, [
       'name' => 'John Doe',
       'type_id' => $person_term_id,
-      'description' => 'Bioinformaticist extrodinaire'
+      'description' => 'Bioinformaticist extrodinaire',
```
Comment (dsenalik) [inline tripal_chado/tests/src/Functional/Services/ChadoTripalPublishTest.php]:
```suggestion
      'description' => 'Bioinformaticist extraordinaire',
```
😄

File: tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php [hunk 7]
```diff
@@ -35,26 +36,22 @@ class ChadoVariablesAPITest extends ChadoTestBrowserBase {
...
   public function testChadoGenerateVariables() {
 
     // TEST DATA.
     // We need something to pull the data for.
     $org = [
       'genus' => 'Tripalus',
       'species' => 'ferox' . uniqid(),
-      'type_id' => 2, //version
+    // Version.
+      'type_id' => 2,
```
Comment (dsenalik) [inline tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php]:
```suggestion
      // Version.
      'type_id' => 2,
```

File: tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php [hunk 8]
```diff
@@ -63,15 +60,16 @@ public function testChadoGenerateVariables() {
     $organism_id = $dbq['organism_id'];
     $this->assertNotEquals(FALSE, $dbq, 'chado_insert_record() unable to insert.');
     $values = [
-      'uniquename' => 'gene'.uniqid(),
+      'uniquename' => 'gene' . uniqid(),
       'organism_id' => $dbq['organism_id'],
-      'type_id' => 2, //version
+    // Version.
```
Comment (dsenalik) [inline tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php]:
```suggestion
      // Version.
```

File: tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php [hunk 9]
```diff
@@ -74,21 +79,23 @@ protected function setUp(): void {
...
+    // foreign key names manufacturer_id -> contact_id.
     $this->connection->insert('1:arraydesign')
       ->fields([
         'name' => 'ArrayDesign No. 1',
-        'platformtype_id' => 1,  // not used, whatever the very first cvterm is
-        'manufacturer_id' => 2,  // 1 is the null contact, defined by chado
+    // Not used, whatever the very first cvterm is.
+        'platformtype_id' => 1,
+    // 1 is the null contact, defined by chado
+        'manufacturer_id' => 2,
```
Comment (dsenalik) [inline tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php]:
```suggestion
        // Not used, whatever the very first cvterm is.
        'platformtype_id' => 1,
        // 1 is the null contact, defined by chado
        'manufacturer_id' => 2,
```

File: tripal_chado/tests/src/Kernel/TripalDBX/ChadoConnectionTest.php [hunk 10]
```diff
@@ -67,9 +69,12 @@ class ChadoConnectionTest extends ChadoTestKernelBase {
...
   protected static array $init_levels = [
-    3, // self::$INIT_CHADO_EMPTY,
-    4, // self::$INIT_CHADO_DUMMY,
-    5, // self::$PREPARE_TEST_CHADO,
+  // self::$INIT_CHADO_EMPTY,.
+    3,
+  // self::$INIT_CHADO_DUMMY,.
+    4,
+  // self::$PREPARE_TEST_CHADO,.
+    5,
```
Comment (dsenalik) [inline tripal_chado/tests/src/Kernel/TripalDBX/ChadoConnectionTest.php]:
```suggestion
    // self::$INIT_CHADO_EMPTY,.
    3,
    // self::$INIT_CHADO_DUMMY,.
    4,
    // self::$PREPARE_TEST_CHADO,.
    5,
```

File: tripal_chado/tests/src/Kernel/TripalDBX/ChadoSchemaTest.php [hunk 11]
```diff
@@ -51,9 +51,12 @@ class ChadoSchemaTest extends ChadoTestKernelBase {
...
   protected static array $init_levels = [
-    3, // self::$INIT_CHADO_EMPTY,
-    4, // self::$INIT_CHADO_DUMMY,
-    5, // self::$PREPARE_TEST_CHADO,
+  // self::$INIT_CHADO_EMPTY,.
+    3,
+  // self::$INIT_CHADO_DUMMY,.
+    4,
+  // self::$PREPARE_TEST_CHADO,.
+    5,
```
Comment (dsenalik) [inline tripal_chado/tests/src/Kernel/TripalDBX/ChadoSchemaTest.php]:
```suggestion
    // self::$INIT_CHADO_EMPTY,.
    3,
    // self::$INIT_CHADO_DUMMY,.
    4,
    // self::$PREPARE_TEST_CHADO,.
    5,
```

File: tripal_chado/tests/src/Functional/ChadoCustomTables/ChadoCustomTableTest.php [hunk 12]
```diff
@@ -29,7 +30,7 @@ class ChadoCustomTableTest extends ChadoTestBrowserBase {
    *
    * @group service manager
    */
-  #[Group('service manager')]
+  #[Group('service')]
```
Comment (dsenalik) [inline tripal_chado/tests/src/Functional/ChadoCustomTables/ChadoCustomTableTest.php]: We have only a total of three instances of group "service"
```
tripal/tests/src/Functional/Services/bulkPgSchemaInstallerTest.php:15:#[Group('service')]
tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php:15:#[Group('service')]
tripal_chado/tests/src/Functional/ChadoCustomTables/ChadoCustomTableTest.php:33:  #[Group('service')]
```
Here I think it should be removed as we already have "service-chado-custom-table" and we don't have "service" for every service type. Plus it's not in the main attribute group. Others in 
```suggestion
```

File: tripal/tests/src/Functional/Services/bulkPgSchemaInstallerTest.php [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+use PHPUnit\Framework\Attributes\Group;
+use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;
+
+/**
+ * Tests the basic functions of the Bulk PostgreSQL Schema Installer.
+ *
+ * @group Tripal
+ * @group Tripal Database
+ */
+#[Group('service')]
```
Comment (dsenalik) [inline tripal/tests/src/Functional/Services/bulkPgSchemaInstallerTest.php]: Proposing `service-installer` - see comment later about only three instances of group "service"
```suggestion
#[Group('service-installer')]
```

File: tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php [hunk 14]
```diff
@@ -1,16 +1,19 @@
...
+use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;
 
 /**
  * Tests the entity lookup service for chado-based content types.
  *
  * @group TripalEntityLookup
  */
-#[Group('TripalEntityLookup')]
+#[Group('tripal-content')]
+#[Group('service')]
```
Comment (dsenalik) [inline tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php]: Proposing "service-collection" because of only three "service" groups as noted elsewhere. Or maybe "service-lookup" would be better?
```suggestion
#[Group('service-collection')]
```

**Review by dsenalik — APPROVED** [review]
Only minor changes from code review of **119** changed files 😓
I did see numerous other coding standards things to deal with in the future.
Noted the test problems on 11.x dev as you described 😩
`phpunit --list-groups` shows all groups following proper naming format 😍
I have comments about eliminating the generic "service" group because there are only a few, and replacing it with a more specific group.
```
 - access (8 tests)
 - access-entity (3 tests)
 - autocomplete (9 tests)
 - bio-cv (14 tests)
 - bio-feature (2 tests)
 - bio-metadata (1 test)
 - bio-organism (8 tests)
 - bio-phylogeny (4 tests)
 - bio-pub (2 tests)
 - biodb-lock (15 tests)
 - biodb-task (13 tests)
 - chado-field (39 tests)
 - chado-importer (15 tests)
 - chado-publish (3 tests)
 - chado-schema (317 tests)
 - chado-storage (25 tests)
 - chado-term (6 tests)
 - consistency (2 tests)
 - drush-command (1 test)
 - field-discovery (2 tests)
 - form (10 tests)
 - importer-datafiles (2 tests)
 - importer-fasta (1 test)
 - importer-gff3 (1 test)
 - importer-newick (1 test)
 - importer-obo (2 tests)
 - importer-phylotree (1 test)
 - importer-pub (3 tests)
 - importer-taxonomy (1 test)
 - layout (7 tests)
 - legacy-api (23 tests)
 - plugin-chado-buddy (10 tests)
 - render (8 tests)
 - service (4 tests)
 - service-chado-custom-table (2 tests)
 - service-citation (1 test)
 - service-collection (15 tests)
 - service-dashboard (1 test)
 - service-file-retriever (5 tests)
 - service-job (4 tests)
 - service-token-parser (16 tests)
 - task-cloner (1 test)
 - task-installer (6 tests)
 - task-preparer (2 tests)
 - task-remover (1 test)
 - task-renamer (1 test)
 - tripal-content (30 tests)
 - tripal-dbx (369 tests)
 - tripal-field (46 tests)
 - tripal-importer (34 tests)
 - tripal-publish (7 tests)
 - tripal-storage (37 tests)
 - tripal-term (11 tests)
```

File: tripal_chado/tests/src/Functional/ChadoCustomTables/ChadoCustomTableTest.php (hunk 12 above)
Comment (laceysanderson) [reply tripal_chado/tests/src/Functional/ChadoCustomTables/ChadoCustomTableTest.php]: Addressed in 45b53ab60a47d607c134956bbd17ee5c31a74dfe. Did as suggested here and removed group.

File: tripal/tests/src/Functional/Services/bulkPgSchemaInstallerTest.php (hunk 13 above)
Comment (laceysanderson) [reply tripal/tests/src/Functional/Services/bulkPgSchemaInstallerTest.php]: Addressed in 45b53ab60a47d607c134956bbd17ee5c31a74dfe. Did as suggested but also added this tag to the chado install task as they are related.

File: tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php (hunk 14 above)
Comment (laceysanderson) [reply tripal_chado/tests/src/Kernel/Services/TripalEntityLookupServiceTest.php]: Addressed in 45b53ab60a47d607c134956bbd17ee5c31a74dfe. Ended up going with service-entity-lookup :-). The service-collection is specific to the config entity collections that we use to import terms, content types, fields.

**Comment by laceysanderson** [comment]
Thanks for the review @dsenalik!!! 😍 This one was a monolith 🙈 In most cases I applied you suggestions directly. In the case of the service group, I addressed this in a single commit (45b53ab60a47d607c134956bbd17ee5c31a74dfe) in order to ensure the new groups were added elsewhere as it made sense to do so.
