### PR TITLE
Fix brittle test by adding check for NCBI maintenance mode

### LINKED ISSUE #2143: Fix brittle tests that depend on external sites
### Task Description

This is an extension of issue #1989 which fixed brittle pubmed tests, so that if pubmed happens to be down when tests are run, they will be gracefully skipped.
This is also related to #1501 where the first thing to try is to retry the download a couple of times. In particular, see this comment https://github.com/tripal/tripal/pull/1679#pullrequestreview-1718265923

The task is to both increase the robustness of downloads from external sites, and if the download still fails, process gracefully in automated tests

This is inspired today because the overnight PHPUnit tests are all failing.
Rerunning one of the failed tests completes without error, highly suggestive of this being a symptom of the external site being down.

### Branch Name

tv4g9-issue2143-fix-brittle-tests-depending-on-external-sites

### Example error messages from https://github.com/tripal/tripal/actions/runs/13612833349/job/38052135242
```
There were 3 failures:

1) Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
One publication should have been retrieved but was not
Failed asserting that 1 matches expected 0.

/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:60

2) Drupal\Tests\tripal_chado\Functional\TaxonomyImporterTest::testTaxonomyImporterSimpleTest
No organism Arabidopsis thaliana found which should have been created
Failed asserting that '0' matches expected 1.

/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TaxonomyImporterTest.php:61

3) Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
There should be more than 0 records found for this query
Failed asserting that null is greater than 0.

/var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:65

--

2 tests triggered 6 PHP warnings:

1) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:287
fopen(): php_network_getaddresses: getaddrinfo for www.ncbi.nlm.nih.gov failed: Temporary failure in name resolution

Triggered by:

* Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:21

* Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:14

2) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:287
fopen(https://www.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=Pubmed&retmax=1&usehistory=y&term=%28%28Populus+%5BTitle%5D%29%29): Failed to open stream: php_network_getaddresses: getaddrinfo for www.ncbi.nlm.nih.gov failed: Temporary failure in name resolution

Triggered by:

* Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:21

3) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:220
Trying to access array offset on int

Triggered by:

* Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:21

* Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:14

4) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:221
Trying to access array offset on int

Triggered by:

* Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:21

* Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:14

5) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:222
Trying to access array offset on int

Triggered by:

* Drupal\Tests\tripal_chado\Functional\PubSearchQueryImporterTest::testPubSearchQueryImporterSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/PubSearchQueryImporterTest.php:21

* Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:14

6) /var/www/drupal/web/modules/contrib/tripal/tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php:287
fopen(https://www.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=Pubmed&retmax=1&usehistory=y&term=%28%28Populus+trichocarpa+%5BTitle%2FAbstract%5D%29%29): Failed to open stream: php_network_getaddresses: getaddrinfo for www.ncbi.nlm.nih.gov failed: Temporary failure in name resolution

Triggered by:

* Drupal\Tests\tripal_chado\Functional\TripalPubLibraryTest::testTripalPubLibraryTestSimpleTest
  /var/www/drupal/web/modules/contrib/tripal/tripal_chado/tests/src/Functional/Plugin/TripalPubLibraryTest.php:14
```

### PR DESCRIPTION
**Pull request by dsenalik**
# Bug Fix

## Description
NCBI is down today, a rare opportunity to fix and test changes for brittle tests!
ncbi_down

The XML request gets the page shown above embedded in it, making it invalid XML.
I have added a validation function to check for this invalid XML, and the test should be skipped instead of failing.

## Testing?
Before this PR, on for example the 8.3, 17, 11.1-dev test, we saw one error and two failures, from testTaxonomyImporterSimpleTest, testPubSearchQueryImporterSimpleTest, and testTripalPubLibraryTestSimpleTest.
https://github.com/tripal/tripal/actions/runs/16540369305/job/46780688235#step:5:13
```
...............................................................  63 / 597 ( 10%)
...III............IFE.F.............IIII....................... 126 / 597 ( 21%)  <- on this line
........I...................................................... 189 / 597 ( 31%)
```
This can only be properly tested today while NCBI is down.
For the automated tests, what we see is the error and failed tests being skipped on this branch.
https://github.com/tripal/tripal/actions/runs/16542674102/job/46786029236#step5:13
```
...............................................................  63 / 596 ( 10%)
...III............ISS.S.............IIII....................... 126 / 596 ( 21%)
.......I....................................................... 189 / 596 ( 31%)
```

### Other symptoms
On this branch, the taxonomy and publication importers will fail gracefully with informative error messages
```
Running 'NCBI Taxonomy Loader' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
Percent complete: 0%. Memory: 37,157,536 bytes.
Importing 1 Taxonomy IDs...
ERROR: Invalid XML returned for taxid 4039, NCBI may be in maintenance mode.
[site http://default] [TRIPAL] ERROR: Invalid XML returned for taxid 4039, NCBI may be in maintenance mode.
Done.


Running 'Publication Loader' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
Initializing publication importer
Step 1 of 7: Retrieving publication data from remote database tripal_pub_library_PMID
ERROR: Invalid XML returned, NCBI may be in maintenance mode.
[site http://default] [TRIPAL] ERROR: Invalid XML returned, NCBI may be in maintenance mode.
ERROR:   ✗ ERROR: Unable to connect to external database to lookup publications
[site http://default] [TRIPAL] ERROR:   ✗ ERROR: Unable to connect to external database to lookup publications
Done.
```

### CODE REVIEW

File: tripal/src/TripalPubLibrary/TripalPubLibraryBase.php [hunk 1]
```diff
@@ -97,4 +97,30 @@ public function __construct(array $configuration, $plugin_id, $plugin_definition
...
+   * @param string $xml
+   *   The XML to be checked.
+   *
+   * @return bool
+   *   Return TRUE if valid, FALSE if not valid.
+   */
+  protected function xmlIsValid(string $xml): bool {
+    $valid = TRUE;
+
+    libxml_use_internal_errors(TRUE);
```
Comment (laceysanderson) [inline tripal/src/TripalPubLibrary/TripalPubLibraryBase.php:116]:
```suggestion
    // Enable user handling of errors so that exceptions are not
    // thrown when invalid XML is read.
    libxml_use_internal_errors(TRUE);
```

File: tripal/src/TripalPubLibrary/TripalPubLibraryBase.php [hunk 2]
```diff
@@ -97,4 +97,30 @@ public function __construct(array $configuration, $plugin_id, $plugin_definition
...
+    $doc = simplexml_load_string($xml);
+    if ($doc === FALSE) {
+      $valid = FALSE;
+    }
+    else {
```
Comment (laceysanderson) [inline tripal/src/TripalPubLibrary/TripalPubLibraryBase.php]:
```suggestion
    // Attempt to load the XML.
    $doc = simplexml_load_string($xml);
    // If SimpleXML fails to parse the XML string then it will return FALSE.
    if ($doc === FALSE) {
      $valid = FALSE;
    }
    // If not, we will check for any errors logged during parsing.
    else {
```

File: tripal/src/TripalImporter/TripalImporterBase.php [hunk 3]
```diff
@@ -614,4 +614,30 @@ public function getArguments() {
...
+   */
+  protected function xmlIsValid(string $xml): bool {
+    $valid = TRUE;
+
+    libxml_use_internal_errors(TRUE);
+    $doc = simplexml_load_string($xml);
+    if ($doc === FALSE) {
+      $valid = FALSE;
+    }
+    else {
```
Comment (laceysanderson) [inline tripal/src/TripalImporter/TripalImporterBase.php]:
```suggestion
    // Enable user handling of errors so that exceptions are not.
    libxml_use_internal_errors(TRUE);
    // Attempt to load the XML.
    $doc = simplexml_load_string($xml);
    // If SimpleXML fails to parse the XML string then it will return FALSE.
    if ($doc === FALSE) {
      $valid = FALSE;
    }
    // If not, we will check for any errors logged during parsing.
    else {
```

File: tripal/src/TripalImporter/TripalImporterBase.php [hunk 4]
```diff
@@ -614,4 +614,30 @@ public function getArguments() {
...
   }
 
+  /**
+   * Validates whether XML is valid or not.
+   *
+   * @param string $xml
+   *   The XML to be checked.
+   *
+   * @return bool
+   *   Return TRUE if valid, FALSE if not valid.
```
Comment (laceysanderson) [inline tripal/src/TripalImporter/TripalImporterBase.php:628]:
```suggestion
   *   Return TRUE if valid, FALSE if not valid.
   * 
   * @see Drupal\tripal\TripalPubLibrary\TripalPubLibraryBase::xmlIsValid().
```

File: tripal/src/TripalPubLibrary/TripalPubLibraryBase.php [hunk 5]
```diff
@@ -97,4 +97,30 @@ public function __construct(array $configuration, $plugin_id, $plugin_definition
...
   }
 
+  /**
+   * Validates whether XML is valid or not.
+   *
+   * @param string $xml
+   *   The XML to be checked.
+   *
+   * @return bool
+   *   Return TRUE if valid, FALSE if not valid.
```
Comment (laceysanderson) [inline tripal/src/TripalPubLibrary/TripalPubLibraryBase.php:107]:
```suggestion
   *   Return TRUE if valid, FALSE if not valid.
   * 
   * @see Drupal\tripal\TripalImporter\TripalImporterBase::xmlIsValid().
```

File: tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php [hunk 6]
```diff
@@ -443,6 +451,8 @@ private function pmidFetch(string $rettype, string $retmod, int $start,
 
     $results = $this->fileretriever->retrieveFileContents($fetch_url, $this->retrieval_options);
 
+    // If NCBI is down for maintenance a HTML page may be embedded in the results.
+    print "\nCP5:";var_dump($results);
```
Comment (laceysanderson) [inline tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php]: Should this still be in the final PR or is it debugging code?

**Review by laceysanderson — COMMENTED** [review]
Code review looks good. I mostly added some comments for future maintenance and most notably `@see` statements in the docblock of both `xmlIsValid()` methods to ensure they are both updated in future.

The only one needing to be addressed is the question regarding the debugging statement which may have been missed in the quick testing of this PR due to the short NCBI maitenance mode window :-)

File: tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php (hunk 6 above)
Comment (dsenalik) [reply tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php]: Oops - will remove

Comment (dsenalik) [reply tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php]: Removed with commit https://github.com/tripal/tripal/pull/2246/commits/6a23cf862dbf90a4c0d5593622551b658c0b19c2

**Review by laceysanderson — APPROVED** [review]
All my concerns are fixed! This is ready to be merged!
