### PR TITLE
Set default terms for field properties when chado mapping is missing.

### LINKED ISSUE #1939: Many field properties do not have defaults set for when chado mapping is not present.
### Tripal Version

4.x-dev

### Drupal Version

10.3.x-dev

### PostgreSQL Version

16

### PHP Version

8.3

### General Description

Exactly as the title says: many field properties do not have defaults set for when chado mapping is not present. This causes field addition to fail whenever the column doesn't exist in the chado mapping. Instead I propose we always add a default for all properties and then if chado mapping provides a more specific term, we use it.

### Steps to reproduce

This is a bit hard to reproduce. I am coming across it while working with an upgraded/migrated chado schema which adds a type_id to the project table. I can't add a chado integer field because there is not yet a mapping for the project.type_id as it's a new column.

1. Start a new Tripaldocker container
2. Add a type_id to the project table so that we have a column without a chado mapping.
```
docker exec CONTAINERNAME drush sql:query "ALTER TABLE chado.project ADD COLUMN type_id bigint"
docker exec CONTAINERNAME drush sql:query "ALTER TABLE chado.project ADD FOREIGN KEY (type_id) REFERENCES chado.cvterm (cvterm_id) ON DELETE SET NULL;"
```
3. Update the chado schema yaml to ensure Tripal knows about this field. This is needed due to the bug mentioned in issue #1936. Apply the following patch to tripal_chado/chado_schema/chado_schema-1.3.yml.
```diff
diff --git a/tripal_chado/chado_schema/chado_schema-1.3.yml b/tripal_chado/chado_schema/chado_schema-1.3.yml
index 7f482d32f..a73cb9c9d 100644
--- a/tripal_chado/chado_schema/chado_schema-1.3.yml
+++ b/tripal_chado/chado_schema/chado_schema-1.3.yml
@@ -4898,6 +4898,13 @@ project:
     description:
       type: text
       not null: FALSE
+    type_id:
+      type: integer
+  foreign keys:
+    cvterm:
+      table: cvterm
+      columns:
+        type_id: cvterm_id
   unique keys:
     project_c1: name
   primary key: project_id
```
4. Clear the cache using `drush cr`
5. Now in the UI, go to Tripal > Page Structure > Project > Manage Fields in the administrative toolbar.
6. Click on "Create a new field" and add a label of "type", select "Chado Fields", then "Chado Integer Field Type" and click Continue.
7. Thanks to the changes in step 2/3 you now see a "type_id" in the "table column" drop down. Select it and set a term for the field such as "rdfs:type".
8. You will now see the reported error message :-( 

### Error messages

```
The website encountered an unexpected error. Try again later.

Exception: Cannot create a StorageProperty object for entity type "tripal_entity", field type "chado_integer_type_default", key "value" as no term was provided in Drupal\tripal\TripalStorage\StoragePropertyBase->__construct() (line 88 of modules/contrib/tripal/tripal/src/TripalStorage/StoragePropertyBase.php).

Drupal\tripal\TripalStorage\StoragePropertyTypeBase->__construct('tripal_entity', 'chado_integer_type_default', 'value', '', 'int', Array) (Line: 32)
Drupal\tripal\TripalStorage\IntStoragePropertyType->__construct('tripal_entity', 'chado_integer_type_default', 'value', '', Array) (Line: 80)
Drupal\tripal_chado\Plugin\Field\FieldType\ChadoIntegerTypeDefault::tripalTypes(Object) (Line: 387)
Drupal\tripal\TripalField\TripalFieldItemBase::schema(Object) (Line: 480)
Drupal\field\Entity\FieldStorageConfig->getSchema() (Line: 2323)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->getDedicatedTableSchema(Object) (Line: 1548)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->createDedicatedTableSchema(Object, NULL) (Line: 1529)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->performFieldSchemaOperation('create', Object) (Line: 695)
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onFieldStorageDefinitionCreate(Object) (Line: 1541)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}() (Line: 1597)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object) (Line: 1540)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onFieldStorageDefinitionCreate(Object) (Line: 85)
Drupal\Core\Field\FieldStorageDefinitionListener->onFieldStorageDefinitionCreate(Object) (Line: 367)
Drupal\field\Entity\FieldStorageConfig->preSaveNew(Object) (Line: 329)
Drupal\field\Entity\FieldStorageConfig->preSave(Object) (Line: 528)
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object) (Line: 483)
Drupal\Core\Entity\EntityStorageBase->save(Object) (Line: 257)
Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object) (Line: 354)
Drupal\Core\Entity\EntityBase->save() (Line: 609)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 264)
Drupal\field_ui\Form\FieldStorageConfigEditForm->save(Array, Object) (Line: 397)
Drupal\field_ui\Form\FieldConfigEditForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 129)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 67)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('field_config_edit_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 48)
Drupal\Core\Entity\EntityFormBuilder->getForm(Object, 'default', Array) (Line: 62)
Drupal\field_ui\Controller\FieldConfigAddController->fieldConfigAddConfigureForm('tripal_entity', 'field_type')
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

### Screenshots

image

### PR DESCRIPTION
**Pull request by laceysanderson**
# Bug Fix

## Description

Many field properties do not have defaults set for when chado mapping is not present. This causes field addition to fail whenever the column doesn't exist in the chado mapping. Instead this PR add a default for all properties and then if chado mapping provides a more specific term, we use it.

## Testing?

1. Start a new Tripaldocker container
2. Add a type_id to the project table so that we have a column without a chado mapping.
```
docker exec CONTAINERNAME drush sql:query "ALTER TABLE chado.project ADD COLUMN type_id bigint"
docker exec CONTAINERNAME drush sql:query "ALTER TABLE chado.project ADD FOREIGN KEY (type_id) REFERENCES chado.cvterm (cvterm_id) ON DELETE SET NULL;"
```
3. Update the chado schema yaml to ensure Tripal knows about this field. This is needed due to the bug mentioned in issue #1936. Apply the following patch to tripal_chado/chado_schema/chado_schema-1.3.yml.
```diff
diff --git a/tripal_chado/chado_schema/chado_schema-1.3.yml b/tripal_chado/chado_schema/chado_schema-1.3.yml
index 7f482d32f..a73cb9c9d 100644
--- a/tripal_chado/chado_schema/chado_schema-1.3.yml
+++ b/tripal_chado/chado_schema/chado_schema-1.3.yml
@@ -4898,6 +4898,13 @@ project:
     description:
       type: text
       not null: FALSE
+    type_id:
+      type: integer
+  foreign keys:
+    cvterm:
+      table: cvterm
+      columns:
+        type_id: cvterm_id
   unique keys:
     project_c1: name
   primary key: project_id
```
4. Clear the cache using `drush cr`
5. Now in the UI, go to Tripal > Page Structure > Project > Manage Fields in the administrative toolbar.
6. Click on "Create a new field" and add a label of "type", select "Chado Fields", then "Chado Integer Field Type" and click Continue.
7. Thanks to the changes in step 2/3 you now see a "type_id" in the "table column" drop down. Select it and set a term for the field such as "rdfs:type".
8. On 4.x you will now see a WSOD and error message as indicated in the linked issue. On this branch the field will add without error.
9. Now create a project page and confirm the page saves without error and that you can set the type_id :-)

### CODE REVIEW

**Review by dsenalik — COMMENTED** [review]
That must have been a pain to add all those! But looks good.
Described test adding as a `Chado Integer Field Type` field worked as advertised.
Then I thought to try adding as a `Chado Type Reference`. When I go to create the project I see 
The website encountered an unexpected error. Try again later.

`TypeError: Drupal\tripal\TripalStorage\TripalStorageBase::addTypes(): Argument #2 ($types) must be of type array, null given, called in /var/www/drupal/web/modules/contrib/tripal/tripal/src/Entity/TripalEntity.php on line 425 in Drupal\tripal\TripalStorage\TripalStorageBase->addTypes() (line 115 of modules/contrib/tripal/tripal/src/TripalStorage/TripalStorageBase.php).`

We are not getting anything from this in `tripal/src/Entity/TripalEntity.php`
```
        // Get the empty property values for this field item and the
        // property type objects.
        $prop_values = $item->tripalValuesTemplate($item->getFieldDefinition());
        $prop_types = get_class($item)::tripalTypes($item->getFieldDefinition());
```

**Review by dsenalik — APPROVED** [review]
The bug I found is now issue #1941 
So there is nothing wrong with this PR

**Comment by laceysanderson** [comment]
Thank you for the review @dsenalik! ❤️ Yes, it was tedious adding all of those 🤪 but the chado mapping UI helped to look them all up in the right format so it was better then it could have been!

File: tripal_chado/src/Plugin/Field/FieldType/ChadoAdditionalTypeTypeDefault.php [hunk 1]
```diff
@@ -216,9 +216,9 @@ public function storageSettingsForm(array &$form, FormStateInterface $form_state
     // If this is an existing field, retrieve its storage settings.
     $storage_settings = $this->getSetting('storage_plugin_settings');
 
-    $type_table = $storage_settings['type_table'] ?? '';
-    $type_column = $storage_settings['type_column'] ?? '';
-    $type_fkey = $storage_settings['type_fkey'] ?? '';
+    $type_table = $storage_settings['type_table'] ?: '';
+    $type_column = $storage_settings['type_column'] ?: '';
+    $type_fkey = $storage_settings['type_fkey'] ?: '';
```
Comment (dsenalik) [inline tripal_chado/src/Plugin/Field/FieldType/ChadoAdditionalTypeTypeDefault.php:221]: This should not have been changed and will be reverted by PR #1942
This change causes a warning that array key does not exist in some cases.
